active_model: gemini # Switch to 'grok'

available_models:
  openai: gpt-5-mini # Or any valid OpenAI model
  grok: grok-4-fast-non-reasoning
  gemini: gemini-2.5-flash

ai_model_connection_timeout: 600

log_level: INFO
