active_model: grok
ai_model_connection_timeout: 600
available_models:
  grok: grok-4-1-fast-non-reasoning
  openai: gpt-5-mini
chroma_persist_path: ./chroma_data
database_provider: chroma
log_level: INFO
